### ISSUE TITLE
[Feature] ok im dumb but what is the main file?

### ISSUE THREAD

**Issue by CoderBOCHENG** [JKamue/SpaceFlight#75]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CoderBOCHENG** [comment]
Can I put this in my blog😮 this game

**Comment by JKamue** [comment]
Hey, great to hear that you are interested!

"Main File" is a relative term. The code for the game is in the SpaceFlight project. The "Main File" theoretically would be [Program.cs](https://github.com/JKamue/SpaceFlight/blob/master/SpaceFlight/Program.cs) since this is the entry point off the game.

What you are looking for is probably the [Game.cs](https://github.com/JKamue/SpaceFlight/blob/b51ea3109475af421320ce95b4a54cab9bf951eb/SpaceFlight/Game/Game.cs) which gets everything in motion to start the simulations.

But maybe you are asking about the "Main file" within the releases which would be SpaceFlight in [this](https://github.com/JKamue/SpaceFlight/releases/download/v0.3/JKM-SpaceFlight-v0.3.zip) Release.

The whole thing is written in C#. You can download the source and open it in VisualStudio. Should work right away, let me know if there are any issues getting it to run.

Feel free to talk about it on your blog. But please include a link to this github repository and credit me and my friends for creating it. Mind sharing a link to your blog?

I have been working on a second version but I stopped developement about a year ago. If you give me your email / discord / whatever I can send you the most recent build. It has some cool features like stage seperation and features more missions as well.

Also you are not dumb lol. If you have any questions about getting it to run that is on me because it was my job to explain it ;)

**Comment by CoderBOCHENG** [comment]
ok thank u! thanks so much

**Comment by CoderBOCHENG** [comment]
i like ur projects

**Comment by JKamue** [comment]
Glad to hear that!

If you have any questions feel free to ask me anytime. 
And if you have any ideas for improvements / find any bugs let me know as well!

**Comment by CoderBOCHENG** [comment]
thanks
